# Generated by Django 4.2.4 on 2023-10-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('album_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('album_name', models.CharField(max_length=50)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=20, null=True)),
                ('album_picture_url', models.CharField(blank=True, max_length=500, null=True)),
                ('bio', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
