# Generated by Django 4.2.4 on 2023-10-25 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='collectors',
        ),
    ]
