# Generated by Django 4.2.4 on 2023-10-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('Playlist_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Playlist_Name', models.CharField(max_length=255)),
                ('Description', models.CharField(blank=True, max_length=500, null=True)),
                ('Visibility', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Playlist',
            },
        ),
    ]
