# Generated by Django 4.2.4 on 2023-10-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='duration',
            field=models.CharField(blank=True, help_text='Duration of the music in MM:SS format.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='music',
            name='release_year',
            field=models.PositiveIntegerField(blank=True, help_text='Year the music was released.', null=True),
        ),
    ]
