# Generated by Django 4.2.4 on 2023-10-26 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_music_duration_music_release_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='release_year',
        ),
    ]
