# Generated by Django 4.2.4 on 2023-10-26 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_remove_music_release_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='name',
            new_name='music_name',
        ),
    ]
