# Generated by Django 4.2.4 on 2023-10-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('MusicianID', models.BigAutoField(primary_key=True, serialize=False)),
                ('MusicianName', models.CharField(max_length=50)),
                ('Genre', models.CharField(blank=True, max_length=20, null=True)),
                ('Bio', models.TextField(blank=True, null=True)),
                ('ProfilePictureURL', models.CharField(blank=True, max_length=500, null=True)),
                ('Region', models.CharField(blank=True, max_length=100, null=True)),
                ('RealName', models.CharField(blank=True, max_length=50, null=True)),
                ('PhoneNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('Nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('OutsidePlatform', models.CharField(blank=True, max_length=100, null=True)),
                ('Nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('PlatformFollowers', models.PositiveIntegerField(default=0)),
                ('is_valid', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'musician',
            },
        ),
    ]
