# Generated by Django 4.2.4 on 2023-10-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_remove_album_collectors'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_albums',
            field=models.ManyToManyField(blank=True, related_name='favorited_by_users_album', to='album.album'),
        ),
    ]
